### ISSUE TITLE
TO-DO List

### ISSUE THREAD

**Issue by alvaro1101** [alvaro1101/PSIS.jl#1]
- [x] Write down the `LICENSE.md`.
- [x] Require Mamba.jl, accept Mamba.Chains as log_like input.
- [ ] ¿Change the name of the package?.
- [x] Improve `README.md`: References...
- [ ] Write down a toy model or generate a sample of fake data for a test.

**Comment by itsdfish** [comment]
Hi @alvaro1101. I've been [corresponding](https://github.com/goedman/Stan.jl/issues/40#issuecomment-294318021) with @goedman about PISIS for julia. We were wondering if you could register your package in METADATA it its ready. Thanks.

**Comment by alvaro1101** [comment]
Hi @fisherc2,
The package need more test. I only test it with the example that I include, but I think it's not enough. I was trying to write a model with fake data but I don't have much time lately, so it's goes slowly.

I could register it as it's with a big disclaimer, but only if someone need it.

Regards.

**Comment by goedman** [comment]
Hi @alvaro1101 

In chapter 7 of the [StatisticalRethinking book and Juliapackage](https://github.com/StatisticalRethinkingJulia/StatisticalRethinking.jl) I would like to use PSIS.jl. To this end I have forked your repository to test it and made some fixes required for Julia v1.5+. The forked version is (for now) at https://github.com/goedman/PSIS.jl. The example script works again (now using StanSample.jl and StatsPlots.jl).
I haven't updated CI integration and other Github action components yet.

My *preference* would be to move the the PSIS.jl repository to the StatisticalRethinking.jl Github organization and and test it further as part of chapter 7 (which uses what you call a toy model in the todo list).

I haven't completely worked through including Turing (and DynamicHMC) support in PSIS.jl, but that would be on my list to do as I get further on in the StatisticalRethinkingTuring.jl project. For now I'm focused on getting it to work for the StatisticalRethinkingStan.jl project. But it will remain a separate package.

Clearly I'll take along your acknowledgements to the authors of PSIS and would like to acknowledge your work. I can also ask the authors for permission again if you feel that would be better.

DO you still think we should change the name? 

Best,
Rob

**Comment by goedman** [comment]
Hi @alvaro1101 

After using and testing PSIS.jl I found that your code worked very well, It needed updates for newer Julia versions and also some extensions to work in the  StatisticalRethinking context I have made these changes and renamed the package to ParetoSmoothedImportanceSampling.jl in StatisticalRethinkingJulia. With the addition of WAIC it really contains a bit more than PSIS methods but for now that is probably ok. I don't think PSIS would be accepted as a package name.

A future version will accommodate Turing and DynamicHMC as well, but the initial release is StanSample.jl based. I typically generate the log_lik matrix in the `generated quantities` section.

The README does acknowledge your (very significant) contribution, but please let me know if you would like to see changes in the acknowledgement.
